### ISSUE TITLE
Needs a generator to mimic the output of an EPV sync

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur-policy-generator#5]
One type of policy people will commonly encounter is the output of the EPV synchronizer. In order to make it easy to demo what this kind of policy will look like, and to make it easy to generate such policies for testing purposes, we should add a generator that mimics its structure and contents.

To do:
- [ ] figure out what the structure of a synchronizer policy is (there might be a spec, or we can work from example)
- [ ] decide what the parameters should be for the user to customize such a policy template
- [ ] add a new generator for that template
- [ ] add a rake task using that generator
- [ ] add the generator to the web UI
- [ ] write bout the generator in the README
